import os

template = """
gensrcs {
    name: "libxcb_{1}_{2}",
    tools: ["libxcb_c_client"],
    srcs: ["{1}.xml"],
    output_extension: "{3}",
    cmd: "$(location libxcb_c_client) $(in) &&" +
         "mv {1}.{3} $(out)",
    export_include_dirs: ["."],
}
"""

def gen_template(name, header=False):
    out = template
    if header:
        out = out.replace("{2}", "header")
        out = out.replace("{3}", "h")
    else:
        out = out.replace("{2}", "source")
        out = out.replace("{3}", "c")
    out = out.replace("{1}", name)
    return out

with open("src/Android.bp", "w") as f:
    f.write("// GENERATED BY gen.py \n")
    for proto in os.listdir("src"):
        if proto.endswith(".xml"):
            name = os.path.basename(proto)[:-4]
            f.write(gen_template(name))
            f.write(gen_template(name, header=True))
